name: build
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build with Vite
        run: npx vite build
      - name: Test with Vitest
        run: npx vitest run --coverage
